[workspace]
members = [
    "core-sdk",
    "extended-sdk",
    "uci-engine",
    "tuning",
    "referee",
    "playground",
    "benchmarking",
    "tests"
]
[profile.release]
opt-level = 3
lto = true